POST {{URL}}/api/product
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

# When product has variations

{
  "name":"Ruslan",
  "description":"This is a description",
  "is_bar_item":false,
  "category_id":2,
  "variations": [
    {
      "name": "20 ml",
      "description":"20 ml of Ruslan",
      "price": 100
    },
    {
      "name": "40 ml",
      "description":"40 ml of Ruslan",
      "price": 200
    }
  ]
}
